### ISSUE TITLE
Risque de takedown DMCA du repo

### ISSUE THREAD

**Issue by Ehstrali** [prixe/lindo#1]
Salut, je viens juste pour vous prévenir qu’il y a un risque très important que ce repo se fasse takedown. TouchEmu, un autre émulateur (ou plutôt fork de no-emu amélioré), vient d’être takedown.
Le lien du dmca: https://github.com/github/dmca/blob/master/2018/2018-02-09-Ankama.md
La procédure est assez lente puisque c’est Ankama mais d’ici 2 mois environ vous allez recevoir la même chose je pense ;).
Bonne continuation pour le développement et essayez d’avoir un gitlab (ou github mais c’est payant) privé de backup au cas ou, on sait jamais !

**Comment by Ehstrali** [comment]
Dans tous les cas je vais essayer de faire appel de la décision je vous tiendrai au courant !

**Comment by Clover-Lindo** [comment]
Le README a bien été modifié en conséquence quelques jours après mon dernier commentaire.

Je ferme cette issue.
