### ISSUE TITLE
RAM consumption

### ISSUE THREAD

**Issue by Stallos11** [prixe/lindo#120]
I'm playing on the same map of the arena, and the RAM increase about 300MB every fight.

Change character doesn't change anything to this.
Here's my ram before stopping lindo and after launching it again, and logging with the same amount of accounts :

![image](https://user-images.githubusercontent.com/49057921/116239986-99de0f80-a763-11eb-9604-f1216451e287.png)
![image](https://user-images.githubusercontent.com/49057921/116239997-9ba7d300-a763-11eb-9582-ffdad588b0ff.png)

Do you have an idea of what can cause this increase of ram every fight ?

**Comment by JulienCoutault** [comment]
Hi, 
We know Lindo use a lot of RAM, it's because it's use Electron. The only thin you can do is to restart Lindo when it use to much RAM. You can also try the last beta, it's must use less RAM than now.
