### ISSUE TITLE
Multiple Accounts Can't set password

### ISSUE THREAD

**Issue by hitagiNcode** [prixe/lindo#122]
I'm trying to set a password for multiple accounts but, I can't set it like before.
Please help can we just remove the passwords ? No one is going to steal my computer and steal dofus items. xd

**Comment by zenoxs** [comment]
For support please ask your question on [matrix](https://matrix.to/#/#lindo-official:matrix.org) or [reddit](https://www.reddit.com/r/LindoApp)
