### ISSUE TITLE
Enemies creature mode activated on hide mounts during fights

### ISSUE THREAD

**Issue by JoaquinGomez1** [prixe/lindo#128]
I've been using this client for a while with my gilfriend and we are both having the same issue, whenever the "hide mounts during fights" feature is enabled all enemies enter creature mode every time we start a new combat.
I'm not sure if this is a bug or if this is on purpose.
PS: Toggling creature mode on and off again will solve this issue.

[View Reference](https://i.imgur.com/WxAPlAN.png)

**Comment by JulienCoutault** [comment]
Hi,
This mod use a glitch to refresh character skin : enter in creature mod and leave it fastly. We know this switch can have some bugs (directly from DT).
Maybe Ankama change something in this function and it create this bug.
I will try to add more time before this call to fix it.

I will keep you posted

**Comment by JulienCoutault** [comment]
@JoaquinGomez1 Do you have the same result with the release 2.6.1 ?

**Comment by JoaquinGomez1** [comment]
To be honest I havent played in a while, but I will try to replicate the issue later today and make an update

**Comment by MirageMaPomme** [comment]
![157AF452-7ABC-4CFA-88DB-E18E40DB731A](https://user-images.githubusercontent.com/81962000/141779976-d41e9091-4255-43c9-8f8d-48f11c53ef8e.jpeg)
The mod « hide mount » can be removed I think as there is an option in Dofus Touch

**Comment by JulienCoutault** [comment]
This feature has been removed
