### ISSUE TITLE
Feature Request - Show the group level and the stars of the monsters out of combat 

### ISSUE THREAD

**Issue by GilbertrdzDev** [prixe/lindo#130]
Hello,

I don't know if this is the right place to request a new feature in the game.

There is the possibility that they add a functionality to be able to see the level of the party, the stars and the experience of the monsters out of combat without having to click and hold.
That is to say, it would serve to be able to see the information of the monsters, which is displayed in a similar way to how the life information bar in combat, but in this case it shows the level of the group, the stars and the experience that will give of the monsters. This would be out of combat on each map, which can be turned on and off with a keyboard shortcut.

Hope you see it as an improvement.

Greetings!

**Comment by JulienCoutault** [comment]
Closed by #134
