### ISSUE TITLE
Lindo error when I try to open it

### ISSUE THREAD

**Issue by mehm92** [prixe/lindo#135]
Please, help me with this error in lindo: "An error occured in your settings, they will be reseted: Syntax Error: Unexpected token < in JSON at position 0"

Whan should i do?

**Comment by JulienCoutault** [comment]
Lindo downloaded something wrongly, delete the folder `game`, you can find in : 
- Windows : %appdata%\lindo (with the Windows search bar)
- Mac : ~/Library/Application Support/lindo/
- Linux : ~/.config/lindo

**Comment by mehm92** [comment]
> Lindo downloaded something wrongly, delete the folder `game`, you can find in :
> 
> * Windows : %appdata%\lindo (with the Windows search bar)
> * Mac : ~/Library/Application Support/lindo/
> * Linux : ~/.config/lindo

I tried to do that, but there is no such folder because the error appears when launching the application and does not allow to download dofus touch. 


Before, I played without problem, then this error began to appear out of nowhere.
![Error](https://user-images.githubusercontent.com/87949475/127082745-b59a27c2-5ec3-4b50-8267-4a7339eb3d23.jpg)
![Folder](https://user-images.githubusercontent.com/87949475/127082752-13fbe846-86ac-43b8-8eb8-8f28e07f62c6.png)

**Comment by mehm92** [comment]
I even did a restoration of the equipment to factory conditions and nothing.

**Comment by MirageMaPomme** [comment]
Hi,
Can you open the "Settings" file with a text editor and past it here ?
Also, removing this file and use the beta of Lindo fixed the issue for some users.

**Warning** your settings will be reseted

**Comment by zarcoko** [comment]
me esta pasando exactamente lo mismo hoy jugue toda la tarde tranquilo, de un momento a otro se puso la pantalla negra, cerre para volver abrir y me sale ese error.

**Comment by AdimDevil** [comment]
{"language":"en","buildVersion":null,"appVersion":null,"macAddress":"N2M6OGI6Y2E6MDE6M2U6YTc=","alertCounter":0,"last_news":null,"appPreferences":null,"option":{"general":{"hidden_shop":false,"hidden_tabs":false,"stay_connected":true,"resolution":{"x":1280,"y":720},"local_content":false,"sound_focus":true,"early":false,"audio_muted":false,"user_agent":"Mozilla/5.0 (Linux; Android 6.0.1; SAMSUNG SM-N920T Build/MMB29K; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/58.0.3029.83 Mobile Safari/537.36"},"shortcuts":{"no_emu":{"new_tab":"ctrl+t","new_window":"ctrl+n","next_tab":"down","prev_tab":"up","activ_tab":"","tabs":["f1","f2","f3","f4","f5","f6","f7","f8","f9","f10"]},"diver":{"end_turn":"backspace","open_chat":"return","active_open_menu":true,"open_menu":"","go_up":"ctrl+up","go_bottom":"ctrl+down","go_left":"ctrl+left","go_right":"ctrl+right"},"spell":["","1","2","3","4","5","6","7","8","9","0","","","","","","","","","","","","","","","","","","",""],"item":["ctrl+1","ctrl+2","ctrl+3","ctrl+4","ctrl+5","ctrl+6","ctrl+7","ctrl+8","ctrl+9","ctrl+0","","","","","","","","","","","","","","","","","","","",""],"interface":{"carac":"c","spell":"s","bag":"i","bidhouse":"h","map":"m","friend":"f","book":"q","guild":"g","conquest":"k","job":"j","alliance":"","mount":"n","directory":"","alignement":"","bestiary":"b","title":"t","achievement":"u","almanax":"x","spouse":"l","shop":"v","goultine":"r"}},"notification":{"private_message":true,"fight_turn":true,"tax_collector":true,"kolizeum":true,"party_invitation":true,"aggression":true,"focus_fight_turn":true},"vip":{"general":{"disable_inactivity":false,"health_bar":true,"health_bar_shortcut":"p","jobsxp":false,"estimator":true,"fightchronometer":true,"hidden_mount":false,"party_info_pp":false,"party_info_lvl":false,"zaapsearchfilter":true},"auto_group":{"active":false,"leader":null,"members":null,"follow_leader":false,"follow_on_map":false,"strict_move":false,"ready":false,"fight":false},"multi_account":{"active":false,"master_password":"","windows":[[]]}}}}

**Comment by AdimDevil** [comment]
well yeah i deleted the setting file on Appdata/Lindo and downloaded the 2.6.0-beta.18 and worked but there is a problem playing with the beta¿?
