### ISSUE TITLE
Can't download the update ! Please try again later (Request failed with status code 404)

### ISSUE THREAD

**Issue by toorpyy** [prixe/lindo#139]
When I try to open de app Lindo No-EMU  appear this sentence  "Can't download the update ! Please try again later (Request failed with status code 404" i don't know how  I  don't know how to solve the problem. Some one can help me?? Thanks

**Comment by MirageMaPomme** [comment]
Can you access to this URL : https://raw.githubusercontent.com/Clover-Lindo/lindo-game-base/master/manifest.json ?

**Comment by Mofitex** [comment]
This happened to me last week, from 5 to 9, my internet provider(Movistar) had some routing bugs and failed to connect to raw.githubusercontent.com and other github pages.
