### ISSUE TITLE
ARM architecture support

### ISSUE THREAD

**Issue by EvannG1** [prixe/lindo#162]
Is it possible to add ARM architecture support for computers/chromebooks with ARM processors ?

Here is what I get when I try to run Lindo on my Chromebook (MediaTek Helio P60T) : 

```shell
cannot execute binary file: Exec format error
```

I don't know if adding arm64 as a parameter in the build command is enough to make it work : 

```json
"release:linux": "electron-builder --linux --x64 --arm64"
```

**Comment by zenoxs** [comment]
Hello I know that this issue is really outdated but we just released the new major version of Lindo in alpha and it supports the arm64 architecture on Linux and Mac: https://github.com/prixe/lindo/releases/tag/v3.0.0-alpha.1
