### ISSUE TITLE
Mac OS infinite downloading

### ISSUE THREAD

**Issue by IAmVitaz** [prixe/lindo#166]
Today I downloaded Lindo 2.6.0.
It is being hanged on updating forever with progress bar filled in completely.
Here are the logs from console if I run TouchEmu from Contents/MacOS folder:
```
info: [UPDATE] Checking for updates
info: [UPDATE] Downloading manifests
info: [UPDATE] Lindo manifest downloaded
info: [UPDATE] Dofus Touch manifest downloaded
info: [UPDATE] Assets map downloaded
info: [UPDATE] Manifests downloaded
info: [UPDATE] Updating required files
info: [UPDATE] Downloaded missing files from one manifest
info: [UPDATE] Downloaded missing files from one manifest
info: [UPDATE] Getting new versions numbers
info: [UPDATE] Applying regex...
info: [UPDATE] Regex applied. Saving files
info: [UPDATE] Files saved
info: [UPDATE] buildVersion: 1.53.6, appVersion: 3.2.5
```
I am on Big Sur 11.6 Mac OS

**Comment by MirageMaPomme** [comment]
Hello !
Where did you downloaded Lindo ? This is not "TouchEmu".
You need to disable your VPN/Proxy (enabled by default on some Mac OS)

But first, you need to use the latest version of Lindo : 2.7.0 (2.7.1 will come soon : it's on beta but fixes an issue with auto-follow)

If this doesn't work, remove the game folder in `~/Library/Application Support/lindo/` and re-launch Lindo.

**Comment by IAmVitaz** [comment]
Thank you! I Tried to download the package via the link on the site and that build caused me a problems.
Just cloned repo and builded using the instructions - everything works like a charm now.
