### ISSUE TITLE
BAIXEI O DOFUS LINDO PELO SITE E TOMEI HACK 

### ISSUE THREAD

**Issue by baron52** [prixe/lindo#168]
baixei o dofus lindo pelo site e alguns dias depois tomei hack,
nunca passei minha senha para ninguem e uso apenas pelo meu computador pessoal e porem so mexeram nos itens mais importantes e nas kamas.

**Comment by JulienCoutault** [comment]
You're an idiot who downloaded Lindo from a fake website. As write here, the only website of lindo is [lindo-app.com](lindo-app.com),
The source code is here and you can see there is nothing to send login to anyone.

**Comment by baron52** [comment]
eu baixei por esse mano, se to falando que tomei hack pelo lindo foi por esse nao por um lindo falso.

**Comment by MirageMaPomme** [comment]
You’ve downloaded a fake one on a wrong website, then you’ve downloaded the right one.
But if you don’t fully uninstall the fake one, it remains on your computer.

Please fully uninstall Lindo by removing the `Lindo` folder in `%appdata%`

**Comment by baron52** [comment]
mano eu falei que instalei no correto, to falando que tem um problema no lindo correto nao foi baixado o falso foi o CORRETO E TOMEI HACK, o correto

**Comment by MirageMaPomme** [comment]
That’s impossible.
Can you show us your download and browsing history ?
You only have to open your download section on your browser (CTRL + J) and search for Lindo
And your browsing history (CTRL + H) and search for Lindo.

We’ll see on which website you’ve downloaded Lindo 🙂

P.S : please do not remove the fake website from your history

**Comment by baron52** [comment]
nao vou discutir com pessoas com um ego alto por suas criaçoes, estou
dizendo que tem falhas e como criadores duvidam isso os levará a ruina

Em qua., 19 de jan. de 2022 às 10:27, MirageMaPomme <
***@***.***> escreveu:

**Comment by baron52** [comment]
Não, não é.

Em qua., 19 de jan. de 2022 às 11:38, MirageMaPomme <
***@***.***> escreveu:

**Comment by JulienCoutault** [comment]
If you say it ...
