### ISSUE TITLE
fermeture du discord lindo

### ISSUE THREAD

**Issue by aejii** [prixe/lindo#192]
wtf guys

**Comment by JulienCoutault** [comment]
Je ne suis pas un habitue de telegram, ca ne donne pas le numero de tel ?

En attendant, j'ai fait un sub reddit www.reddit.com/r/lindo_no_emu

**Comment by JulienCoutault** [comment]
Je suis en train d'importer Lindo sur gitlab https://gitlab.com/lindo-no-emu

**Comment by MirageMaPomme** [comment]
J’ai une copie locale de master qui date de ma dernière PR, donc assez récente 😬

**Comment by TheKetur55** [comment]
R.I.P

**Comment by MirageMaPomme** [comment]
> Je ne suis pas un habitue de telegram, ca ne donne pas le numero de tel ?

Il suffit de masquer ton numéro de téléphone dans les paramètres de Telegram.
Ensuite il faut créer un groupe, et inviter via n°téléphone ou user (@machinTruc)

**Comment by aejii** [comment]
backup telegram : https://t.me/+rmcVq3A9jbE5ZWFk
et oui sur telegram ton numéro est masqué (sauf pour tes amis)

**Comment by zenoxs** [comment]
Du coup on a mis en place un serveur matrix pour la collaboration : https://matrix.to/#/#lindo-official:matrix.org
