### ISSUE TITLE
Ajout de l'icône de Lindo pour les builds Linux

### ISSUE THREAD

**Issue by Eveldee** [prixe/lindo#2]
Bonjour, en téléchargeant Lindo pour Linux, je me suis rendu compte que l'icône n'est pas incluse dans l'archive. Ceci pose problème pour créer un raccourci adéquat à sa distrib.

Suggestion: Ajouter l'icône de Lindo dans l'archive en format .png/.xpm.

Exemple: https://prntscr.com/j5id4d

**Comment by Clover-Lindo** [comment]
Bonjour,
Je n'investis personnellement plus autant de temps qu'avant dans le développement de Lindo, et de mon point de vue ça me semble être un problème assez secondaire.
En revanche, si tu sais quoi faire pour corriger ce soucis je suis très largement ouvert aux Pull Requests!

**Comment by SwiTool** [comment]
@Clover-Lindo Ca serait pas simplement l'icone du build à changer ?
https://github.com/prixe/lindo/blob/master/package.json#L127

**Comment by Clover-Lindo** [comment]
Je suis pas sûr, le path a l'air correct, l'image existe bien, et [la doc d'electron-builder](https://www.electron.build/configuration/linux) a pas l'air de donner des spécifications sur le format ou la taille de l'image 😕 

Je pose ça là, à voir si ça fonctionne
https://github.com/electron-userland/electron-builder/issues/2269#issuecomment-342168989
