### ISSUE TITLE
[New Mod] party-info

### ISSUE THREAD

**Issue by axel012** [prixe/lindo#20]
I want to upload a mod that i made for getting party level and prospection, don't know if i am in the right section or not

[party-info.zip](https://github.com/prixe/lindo/files/2665111/party-info.zip)

**Comment by JulienCoutault** [comment]
Hi, 
Your mod seems be good, now you need to setin in lindo
You can see commit [8e67e64](https://github.com/prixe/lindo/commit/8e67e64864964cc9683da3fcd654c1245c80fefa) and few after to see how i did for an other mod
If you create a fork to prepare your pull request, i can help you

**Comment by axel012** [comment]
Pull created!
