### ISSUE TITLE
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)

### ISSUE THREAD

**Issue by TommasoBarberis** [prixe/lindo#223]
Hi all,

I've installed Lindo 2.7.3 using the .deb file on ubuntu 22.04 LTS x86_64  with a nvidia graphic card (geforce gt 1030). When starting Lindo I've the following error:

``` 
info 16:39:03 : [SETTING] Checking settings integrity..
info 16:39:03 : [SETTING] Settings are correct.
mesa: for the --simplifycfg-sink-common option: may only occur zero or one times!
mesa: for the --global-isel-abort option: may only occur zero or one times!
mesa: for the --amdgpu-atomic-optimizations option: may only occur zero or one times!
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
warn 16:39:04 : [UPDATE] Skipping app check
info 16:39:04 : [UPDATE] Game update started..
[13513:0725/163904.735205:FATAL:gpu_data_manager_impl_private.cc(415)] GPU process isn't usable. Goodbye.
Instruction non permise (core dumped)
```

**Comment by zenoxs** [comment]
Hey, it's looks like it related to your Linux environment. You should try to search more information on google with these keywords `Ubuntu libva error: vaGetDriverNameByIndex()`. 

But before that, maybe you could try to install the new V3 versions https://github.com/prixe/lindo/releases/tag/v3.0.0-alpha.5 which uses a more modern version of chromium.
Let me know how it goes

**Comment by TommasoBarberis** [comment]
It seems to work fine with the v3.0.0-alpha.5. Thank you for your help! :smile:

**Comment by zenoxs** [comment]
You're welcome, great news :)
