### ISSUE TITLE
Can't create a new account from Lindo: 

### ISSUE THREAD

**Issue by Suniron** [prixe/lindo#245]
Hello,

I got the popup error "Une erreur est survenue" when i'm trying to create a new account.
Meanwhile, this link is automatically opened in my browser: https://account.ankama.com/fr/dofus-touch-create-guest.

Thank's by advance.

Tested on Windows 11 and Linux (Ubuntu 22.04)

**Comment by zenoxs** [comment]
Hey thank you for the bug but I think we won't support this feature. We prefer to focus on other things and you can still create an account as well from the Ankama website. Thank you :)
