### ISSUE TITLE
Full screen mode not working properly

### ISSUE THREAD

**Issue by UnlikelyBuddy1** [prixe/lindo#255]
![Untitled](https://user-images.githubusercontent.com/52712038/204094796-3186e08c-5b61-4fa4-9624-ddebdf9802f1.png)

When refreshing the page, It removed that bottom section, but then the title bar re-appears.
I remember seeing a section with a `height : calc(100vh -30px)` which I believe is the title bar height. So maybe the easy fix would just be to make a condition so that if full-screen, this attribute becomes `height : 100vh`

btw, I've trying to reach devs for some time, I would like to contribute 👍

**Comment by zenoxs** [comment]
Hey! Thank you for reporting the problem. I think it may occur only on a specific platform because I cannot reproduce the problem on my own device (macOS). By the way, if you want to contribute you can reach me on discord (Zenox/Tipper#7321)
