### ISSUE TITLE
LightGreen.png - Update Bug

### ISSUE THREAD

**Issue by Roast-Lord** [prixe/lindo#26]
So today i opened my lindo and  he couldn't update because the launcher couldn't find the file "LightGreen.png" and delete it from "\AppData\Roaming\Lindo\game\assets\ui\bars", a solution for this is creating an LightGreen.png file an put on the directory and open lindo again, it worked for me and may help others until this bug is fixed. 

Sorry for my bad english.

**Comment by JulienCoutault** [comment]
Hi,

Can you explain when lindo search "LightGreen.png" ? And what version of Lindo on each OS you use ?

Cause, for me, on Windows 10 and Ubuntu 18.04, Lindo 2.3 works without this file.

Look what i have in "\AppData\Roaming\Lindo\game\assets\ui\bars" : 
- aqua.png
- background.png
- blue.png
- green.png
- light-orange.png
- orange.png
- pink.png
- purple.png
- res.png
- transparentBg.png
- yellow.png

**Comment by Roast-Lord** [comment]
I'm using windows 10, lindo version 2.3

Lindo searches this file while downloading the last update for me, the download is interrupted and a message shows up: "No such file or directory unlink C:\Users\\AppData\Roaming\Lindo\game\assets\ui\bars"

**Comment by JulienCoutault** [comment]
Fix by 94e29742d355ab55447a915f6f362ed5469ba8b6
