### ISSUE TITLE
Serveur privée

### ISSUE THREAD

**Issue by Shad0w59i** [prixe/lindo#262]
Bonjour,

Je dispose d'un serveur dofus touch.
J'aimerais le tester avec Lindo mais je ne sais pas comment faire pour ce connecter sur mon serveur privée avec Lindo

J'utilise https://github.com/bleugateau/Arkanic-Touch pour le serveur

Merci

**Comment by JulienCoutault** [comment]
Salut,
J'avais regardé comment faire et il me semble qu'il suffisait juste de changer le lien vers le serveur.
Si mes souvenir sont bons, dans le fichier `packages/main/constants/index.ts`, remplacer la valeur de `DOFUS_ORIGIN ` (ou `DOFUS_EARLY_ORIGIN` pour garder l'option de jouer sur les serveurs officiels) par le lien vers ton serveur privé

**Comment by Shad0w59i** [comment]
J'ai un erreur "Une erreur inconnue est survenue"
Je dois pas changer les port dans Lindo ?

Info:
    AUTH_PORT: 3014,
    WORLD_PORT: 666,

**Comment by JulienCoutault** [comment]
La, je ne sais pas, j'ai l'impression que le port n'est jamais spécifié (peut être qu'ajouter `:666` dans l'url suffit)

Pour l'auth (j'avais oublié cette partie), ca se passe dans le fichier `script.js` que Lindo dl depuis Dofus directement

**Comment by Shad0w59i** [comment]
Je vais essayer demain, je reviens vers toi pour te tenir informer 👍🏼 
Merci

**Comment by Shad0w59i** [comment]
> La, je ne sais pas, j'ai l'impression que le port n'est jamais spécifié (peut être qu'ajouter `:666` dans l'url suffit)
> 
> Pour l'auth (j'avais oublié cette partie), ca se passe dans le fichier `script.js` que Lindo dl depuis Dofus directement

Je ne voie pas a quel endroit je dois modifier dans le fichier script.js

**Comment by JulienCoutault** [comment]
Le fichier dois se trouver dans `%appData%/Lindo/game/build/script.js` si cela n'a pas changer

Sur Linux,  si Linux c'est dans `.config/lindo/game/build/script.js`

Tu peux checker https://github.com/JulienCoutault/LindoMusic , c'etait un repo qui permettait de changer les musiques dans Lindo qui modifiait le fameux `script.js`, et plus particulièrement le commit https://github.com/JulienCoutault/LindoMusic/commit/bd552d434eb52121d65101388182aaf83ef0f5f7 qui fixait la recup du `script.js` pour Linux

**Comment by Shad0w59i** [comment]
> Le fichier dois se trouver dans `%appData%/Lindo/game/build/script.js` si cela n'a pas changer
> 
> Sur Linux, si Linux c'est dans `.config/lindo/game/build/script.js`
> 
> Tu peux checker https://github.com/JulienCoutault/LindoMusic , c'etait un repo qui permettait de changer les musiques dans Lindo qui modifiait le fameux `script.js`, et plus particulièrement le commit [JulienCoutault/LindoMusic@bd552d4](https://github.com/JulienCoutault/LindoMusic/commit/bd552d434eb52121d65101388182aaf83ef0f5f7) qui fixait la recup du `script.js` pour Linux
