### ISSUE TITLE
Ecran gris sur la v2.0.0 beta 8 version mac

### ISSUE THREAD

**Issue by simobenso** [prixe/lindo#3]
Bonjour, 

Je me suis rendu compte que la release beta 8 sur la version mac OS présente un bug au lancement de l'application, l'écran reste gris et ce après avoir testé sur deux différentes machines : 

- Macbook Pro 2015 macOS Sierra
- Mac Pro 2009 macOS Yosemite

**Comment by Clover-Lindo** [comment]
Merci de l'avoir signalé!

Après en avoir parlé sur Discord, il s'avère que le problème venait de la lib flex-layout. Cette lib a été rétrogradée dans [ce commit](https://github.com/Linuxydable/lindo/commit/9d02b3d73004a3c2908ce87870c029c1e62510e0), le problème devrait être corrigé maintenant.

Je ferme cette issue.
