### ISSUE TITLE
Interface graphique comme sur tablette

### ISSUE THREAD

**Issue by Mortatiina** [prixe/lindo#34]
Bonjour, 

Est-il possible de mettre l'interface comme sur tablette avec la barre des sorts en bas ? Je ne trouve pas dans les options ^^
sinon comptez vous ajouter la possibilité ?
Merci!

**Comment by JulienCoutault** [comment]
Bonjour,

Ce phenomene est directement gere par DT. Lorsque la resolution est suffisament large, la barre des sorts se place a droite, sinon en bas.

Pour avoir la barre des sorts bas, il faut reduire la largeur de la fenetre.

Comme je l'ai dit, ce comportement est directement liee a DT (Lindo n'interagit pas avec l'interface), ajouter une option pour permettre de gerer ca manuellement risque d'etre complexe et n'est pas a l'ordre du jour

**Comment by Mortatiina** [comment]
Ha d'accord! merci bien :)!
