### ISSUE TITLE
(Lindo:4060): Pango-ERROR

### ISSUE THREAD

**Issue by Gambl3r08** [prixe/lindo#36]
(Lindo:4060): Pango-ERROR **: 17:38:01.125: Harfbuzz version too old (1.4.2)

`trap' para punto de parada/seguimiento (`core' generado)

**Comment by JulienCoutault** [comment]
Can you explain ?

**Comment by Gambl3r08** [comment]
When i try to exec Lindo in Manjaro throw that error. 
Manjaro xfce
Pango 1.44.6+2

**Comment by JulienCoutault** [comment]
Lindo is not support on arch linux,
We have a voluntary to try it but I can't promise you anything (you can come to the discord to talk with him)

**Comment by JulienCoutault** [comment]
He tried, he successed to run Lindo 2.2.3 and 2.3.2 without Pango error,

Sorry I don't use Manjaro, I can't help you more

**Comment by Yunkz** [comment]
I have the same problem with Fedora 31.
I found this : https://github.com/electron/electron/issues/20348

**Comment by JulienCoutault** [comment]
Thanks for the link,

Wich one version did you try ?
The 2.3.x works with electron 4.1.3

**Comment by Yunkz** [comment]
I've tried 2.2.x it has not worked.
I just tried with 2.3.1 and I confirm that it works.

**Comment by JulienCoutault** [comment]
Good to read this

@Gambl3r08 can you confirm Lindo 2.3.1 works for you ?

**Comment by Gambl3r08** [comment]
Not really ,the only way it works is making a downgrade to pango-1:1.43.0-1, run lindo and recompiling the latest version of Pango so as not to break the system dependencies

**Comment by JulienCoutault** [comment]
So lindo works for you ?

Did you try with lindo 2.3 or you did this way before ?
