### ISSUE TITLE
Change pass/ready shortcut from delete to another shortcut

### ISSUE THREAD

**Issue by amboulouma** [prixe/lindo#38]
This can cause a turn passage when writing and handling multiple accounts, and can cause a challenge to fail, a sudden death, etc.

Please change it.

**Comment by JulienCoutault** [comment]
It's the default value, you can change it in Lindo options

**Comment by amboulouma** [comment]
Where can I find them? I am running the linux Lindo version.

**Comment by amboulouma** [comment]
@JulienCoutault Found, thank you!

**Comment by JulienCoutault** [comment]
You're welcome  :wink:

His anyone else want to know :
The option is `Configure shortcut` > `Various` > `End your turn / Ready (Fight)`
