### ISSUE TITLE
Vulnerabilite dans electron 1.8.2

### ISSUE THREAD

**Issue by JulienCoutault** [prixe/lindo#4]
Bonjour,
La version d'electron du repo (version 1.8.2) contient des vulnérabilités (<https://nodesecurity.io/advisories?search=electron&version=1.8.2>), il serait bien de passer a la version 2.0.0.

**Comment by Clover-Lindo** [comment]
Bonjour,
Merci pour cette information!
Malheureusement, changer de majeure prend énormément de temps, on avait déjà essayé il me semble et c'est pour ça qu'on est resté sur la version 1.
J'ai regardé vite fait, on dirait qu'il y a une solution alternative, mais je ne suis pas sûr qu'on soit concerné.
Je ne pense pas prendre le temps de m'en occuper, mais je reste réactif aux Pull Requests, si jamais
