### ISSUE TITLE
A problem when I'm trying to do npm-install

### ISSUE THREAD

**Issue by hitagiNcode** [prixe/lindo#41]
Hello, @JulienCoutault .

I'm an indie game developer I'm good at C# and Unity, blender. But I'm clearly new in Node.js, Angular and electron. I wanna add new features to our lindo. I wanna be usefull if you help me to fix my small issue or issues with time :) so please how can I upgrade node-sass version of lindo to  4.13.0.  or I should downgrade my node.js ?

Whenever I try to do npm install it gives me an error. I've try to upgrade an downgrade my node-sass -v, and tried to install node js 12x. node didn't work.
I also tried deleting and installing without "package-lock.json"
```
My versions are:
Node v13.0.1
Npm v6.12.1
node-sass       4.13.0  (Wrapper)       [JavaScript]
libsass         3.5.4   (Sass Compiler) [C/C++]

```
My versions:
Node v13.0.1
Npm v6.12.1
node-sass       4.13.0  (Wrapper)       [JavaScript]
libsass         3.5.4   (Sass Compiler) [C/C++]

[2019-11-05T14_43_30_497Z-debug.log](https://github.com/prixe/lindo/files/3815896/2019-11-05T14_43_30_497Z-debug.log)
```
here is my error log:
50999 verbose stack Error: node-sass@4.9.3 postinstall: `node scripts/build.js`
50999 verbose stack Exit status 1
50999 verbose stack     at EventEmitter.<anonymous> (C:\Users\barisgun\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
50999 verbose stack     at EventEmitter.emit (events.js:210:5)
50999 verbose stack     at ChildProcess.<anonymous> (C:\Users\barisgun\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
50999 verbose stack     at ChildProcess.emit (events.js:210:5)
50999 verbose stack     at maybeClose (internal/child_process.js:1028:16)
50999 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
51000 verbose pkgid node-sass@4.9.3
51001 verbose cwd C:\Users\barisgun\lindo
51002 verbose Windows_NT 10.0.18362
51003 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\barisgun\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
51004 verbose node v13.0.1
51005 verbose npm  v6.12.1
51006 error code ELIFECYCLE
51007 error errno 1
51008 error node-sass@4.9.3 postinstall: `node scripts/build.js`
51008 error Exit status 1
51009 error Failed at the node-sass@4.9.3 postinstall script.
51009 error This is probably not a problem with npm. There is likely additional logging output above.
51010 verbose exit [ 1, true ]



```

**Comment by JulienCoutault** [comment]
Hi @hitagiNcode,

I saw nodejs 13 works only with node-sass 13+ https://www.npmjs.com/package/node-sass
I upgraded node-sass in the branch `libs-update`  (https://github.com/prixe/lindo/commit/fa2d74aa0ebf7c5303bdc3934bb2354f3aaf025d) ,correspond to the Lindo beta with new version of library, try on this

I will talk with other to see if wee updrade it now on `master`

**Comment by hitagiNcode** [comment]
Thank you so much JulienCoutault !

**Comment by JulienCoutault** [comment]
You're welcome
