### ISSUE TITLE
Erreur lors de l'étape "npm install"

### ISSUE THREAD

**Issue by Suniron** [prixe/lindo#49]
Bonjour,

Côté machine, je suis sous Ubuntu 18.04 avec node 11.15.0.

Après avoir récupéré projet avec `git clone`, je fais `npm install` et au bout de quelques instants l'installation s'interrompt avec le log suivant:

```42117 verbose stack Error: node-sass@4.9.3 postinstall: `node scripts/build.js`

42117 verbose stack Exit status 1

42117 verbose stack     at EventEmitter.<anonymous>(/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)

42117 verbose stack     at EventEmitter.emit (events.js:210:5)

42117 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)

42117 verbose stack     at ChildProcess.emit (events.js:210:5)

42117 verbose stack     at maybeClose (internal/child_process.js:1028:16)

42117 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)

42118 verbose pkgid node-sass@4.9.3

42119 verbose cwd /home/etienne/developpement/electron/lindo

42120 verbose Linux 5.0.0-36-generic

42121 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"

42122 verbose node v13.1.0

42123 verbose npm  v6.12.1

42124 error code ELIFECYCLE

42125 error errno 1

42126 error node-sass@4.9.3 postinstall: `node scripts/build.js`

42126 error Exit status 1

42127 error Failed at the node-sass@4.9.3 postinstall script.

42127 error This is probably not a problem with npm. There is likely additional logging output above.

42128 verbose exit [ 1, true ]```

J'ai testé diverses solutions par rapport à node-sass, si quelqu'un à une piste je suis preneur :-).

Merci d'avance.

**Comment by JulienCoutault** [comment]
Meme probleme que #41 
Utilise la branch `libs-update`, c'est la beta de lindo avec des bibliotheques mise a jour

**Comment by Suniron** [comment]
Merci, pb résolu en utilisant le package npm "n" afin d'avoi rune version de node compatible.
