### ISSUE TITLE
Erreur : "Error occured on version check process."

### ISSUE THREAD

**Issue by JanmotTimothee** [prixe/lindo#5]
Bonjour,

J'ai cette erreur qui reviens juste aprés l'instalation : "Error occured on version check process."
Des idées ? je suis sur windows 7.

**Comment by JanmotTimothee** [comment]
Mon fichier settings : 
`{
  "language": "en",
  "buildVersion": null,
  "appVersion": null,
  "macAddress": "xx:xx:xx:xx:xx:xx",
  "alertCounter": 0,
  "vip_id": null,
  "last_news": null,
  "appPreferences": null,
  "option": {
    "general": {
      "hidden_shop": false,
      "hidden_tabs": false,
      "stay_connected": true,
      "resolution": {
        "x": 1280,
        "y": 720
      },
      "local_content": false,
      "sound_focus": true,
      "user_agent": "Mozilla/5.0 (Linux; Android 6.0.1; SAMSUNG SM-N920T Build/MMB29K; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/58.0.3029.83 Mobile Safari/537.36"
    },
    "shortcuts": {
      "no_emu": {
        "new_tab": "ctrl+t",
        "new_window": "ctrl+n",
        "next_tab": "down",
        "prev_tab": "up",
        "activ_tab": "",
        "tabs": [
          "f1",
          "f2",
          "f3",
          "f4",
          "f5",
          "f6",
          "f7",
          "f8",
          "f9",
          "f10"
        ]
      },
      "diver": {
        "end_turn": "backspace",
        "open_chat": "return"
      },
      "spell": [
        "",
        "1",
        "2",
        "3",
        "4",
        "5",
        "6",
        "7",
        "8",
        "9",
        "0",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      "item": [
        "ctrl+1",
        "ctrl+2",
        "ctrl+3",
        "ctrl+4",
        "ctrl+5",
        "ctrl+6",
        "ctrl+7",
        "ctrl+8",
        "ctrl+9",
        "ctrl+0",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      "interface": {
        "carac": "c",
        "spell": "s",
        "bag": "i",
        "bidhouse": "h",
        "map": "m",
        "friend": "f",
        "book": "q",
        "guild": "g",
        "conquest": "k",
        "job": "j",
        "alliance": "",
        "mount": "n",
        "directory": "",
        "alignement": "",
        "bestiary": "b",
        "title": "t",
        "achievement": "u",
        "almanax": "x",
        "spouse": "l",
        "shop": "v",
        "goultine": "r"
      }
    },
    "notification": {
      "private_message": true,
      "fight_turn": true,
      "tax_collector": true,
      "kolizeum": true,
      "party_invitation": true,
      "aggression": true,
      "focus_fight_turn": true
    },
    "vip": {
      "general": {
        "disable_inactivity": false,
        "health_bar": true,
        "health_bar_shortcut": "p",
        "estimator": true
      },
      "auto_group": {
        "active": false,
        "leader": null,
        "members": null,
        "follow_leader": false,
        "follow_on_map": false,
        "strict_move": false,
        "ready": false,
        "fight": false
      },
      "multi_account": {
        "active": false,
        "master_password": "",
        "windows": [
          []
        ]
      }
    }
  }
}
`

**Comment by Clover-Lindo** [comment]
Cette erreur se produit lorsque qu'il y a un problème de communication entre le client et le serveur de Lindo.
En dehors d'une panne globale, ça peut éventuellement être dû à cause d'un proxy qui bloquerait la connexion, ou d'un anti-virus par exemple.

Depuis l'introduction de l'Auto Update dans la 2.0.0-beta.11, la communication avec notre serveur est devenue optionnelle et ce message ne devrait donc plus apparaître.

Je t'invite à récupérer la 2.0.0-beta.13 disponible dans les releases. Éventuellement, la compilation de la 2.0.0 définitive est en cours, elle sera disponible d'ici une dizaine de minutes sur la même page.
https://github.com/prixe/lindo/releases

Si tu étais bien sur une version supérieur à la beta-11, tu peux ré-ouvrir cette issue pour qu'on puisse voir qu'est-ce qui a pu déclencher ce message.
