### ISSUE TITLE
wayland error

### ISSUE THREAD

**Issue by umensa** [prixe/lindo#59]
Lindo do not execute on wayland.
It return this error message :

> (Lindo:7238): Gtk-WARNING **: xx:xx:xx.xxx: cannot open display: wayland-0

Even with root privilege, the same error occurs.

**Comment by umensa** [comment]
The Lindo's version 2.2.3 works fine under wayland.
However the version 2.4.0 execute only on xorg.
I am using ubuntu 18.04.4 lts.
I hope that this helps you to fix the bug.

**Comment by umensa** [comment]
the debug.log file content

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@6.14.4
3 info using node@v8.10.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle lindo@2.4.0~prestart: lindo@2.4.0
6 info lifecycle lindo@2.4.0~start: lindo@2.4.0
7 verbose lifecycle lindo@2.4.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle lindo@2.4.0~start: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/umensa/Downloads/dofus/lindo/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
9 verbose lifecycle lindo@2.4.0~start: CWD: /home/umensa/Downloads/dofus/lindo
10 silly lifecycle lindo@2.4.0~start: Args: [ '-c', 'electron ./' ]
11 silly lifecycle lindo@2.4.0~start: Returned: code: 1  signal: null
12 info lifecycle lindo@2.4.0~start: Failed to exec start script
13 verbose stack Error: lindo@2.4.0 start: `electron ./`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid lindo@2.4.0
15 verbose cwd /home/umensa/Downloads/dofus/lindo
16 verbose Linux 4.15.0-91-generic
17 verbose argv "/usr/bin/node" "/usr/local/bin/npm" "start"
18 verbose node v8.10.0
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 1
22 error lindo@2.4.0 start: `electron ./`
22 error Exit status 1
23 error Failed at the lindo@2.4.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by umensa** [comment]
**Cannot open display: :0 with Electron-based applications**

Make sure you haven't set GDK_BACKEND=wayland. Setting it globally will break Electron apps. 

Found on the archWiki [https://wiki.archlinux.org/index.php/Wayland#Troubleshooting](url)
However, this do not solve the issue.
The Lindo's version 2.2.3 works fine under wayland session.
And the version 2.4.0 execute only on xorg session.

**Comment by umensa** [comment]
This issue is fixed by installing the .deb build.
Lindo execute on the wayland session as expected.

**Comment by JulienCoutault** [comment]
It's was unexpected but it's a good news.
