### ISSUE TITLE
Ubuntu 18.04 Gets stuck on Downloading

### ISSUE THREAD

**Issue by IvanTurgenev** [prixe/lindo#6]
Also had to install gconf module, what debug information do you need?

**Comment by IvanTurgenev** [comment]
Works on 16.04 copied the lindo configuration folder from 16.04 to 18.04 and it seems to work

**Comment by Clover-Lindo** [comment]
So basically there are two issues here.
- Downloading stuck (happened on many Windows machines as well)
- The need to install libgconf-2-4 separately

I don't know what's the best way to split issues on GitHub so I will leave it this way.

I don't have any ETA to provide but these are definitely issues to be fixed.

**Comment by sudogooglex** [comment]
On Ubuntu 18.10, in /app/window/official-game-update/official-game-update.component.ts,
sometimes the request callback contains a **response.statusCode** 404 but **err** is undefined.

```
download(url, json = false, weight = 1) {
        let currentProgress = 0;
        return new Promise((resolve, reject) => {
            progress(request(url, (err, response, body) => {
                console.log(response.statusCode); // Add this to see the error
                if (err) {
                    reject(err);
                }
                else if (response.statusCode >= 300) {
                    reject(response.statusCode);
                }
                else {
                    this.addProgress(weight - currentProgress);
                    if (json)
                        resolve(JSON.parse(body));
                    else
                        resolve(body);
                }
            })).on("progress", (state) => {
                let progress = state.percent * weight;
                this.addProgress(progress - currentProgress);
                currentProgress = progress;
            });
        });
    }
```

**Comment by Clover-Lindo** [comment]
@sudogooglex I have never seen this before. Only on Ubuntu? Which file failed?

**Comment by sudogooglex** [comment]
@Clover-Lindo Yes only on Ubuntu. The failed files are fixes.js and styles-native.css.

Well, this time, it seems Lindo couldn't download some files : no response.
The get request was sent but for some reason, wasn't recieved with any error code.
This gives the following logs :

> [UPDATE] Checking for updates
> main.bundle.js:7171 1
> main.bundle.js:7173 2
> main.bundle.js:7371 https://raw.githubusercontent.com/Clover-Lindo/lindo-game-base/master/manifest.json  get
> main.bundle.js:7371 https://proxyconnection.touch.dofus.com/manifest.json  get
> main.bundle.js:7371 https://proxyconnection.touch.dofus.com/assetMap.json  get
> main.bundle.js:7397 end !
> main.bundle.js:7373 https://raw.githubusercontent.com/Clover-Lindo/lindo-game-base/master/manifest.json  ok 200 null
> main.bundle.js:7397 end !
> main.bundle.js:7373 https://proxyconnection.touch.dofus.com/manifest.json  ok 200 null
> main.bundle.js:7397 end !
> main.bundle.js:7373 https://proxyconnection.touch.dofus.com/assetMap.json  ok 200 null
> main.bundle.js:7180 3
> main.bundle.js:7188 4
> main.bundle.js:1973 [UPDATE] Updating required files
> main.bundle.js:7198 5
> main.bundle.js:7204 5 bis
> main.bundle.js:7557 downloadMissingFiles Object
> main.bundle.js:7577 downloadMissingFiles out
> main.bundle.js:1973 [UPDATE] Downloaded missing files from one manifest
> main.bundle.js:7557 downloadMissingFiles Object
> main.bundle.js:7371 https://proxyconnection.touch.dofus.com/build/script.js  get

As you can see, I have a response for manifest.json and assetMap.json, but not for script.js. When I try it in an other browser, it's ok. But in Lindo, the gui keep displays 'Downloading'.

I have tryed to change this line (/src/app/window/official-game-update/official-game-update.component.ts:87)

`this.loadCurrentLindoManifest(), this.loadCurrentManifest(), this.loadCurrentAssetMap(), this.loadVersions(), this.loadCurrentRegex(),`
to this line
`this.loadCurrentAssetMap(), this.loadCurrentRegex(),`

> https://raw.githubusercontent.com/Clover-Lindo/lindo-game-base/master/manifest.json  get
> main.bundle.js:7372 https://proxyconnection.touch.dofus.com/manifest.json  get
> main.bundle.js:7372 https://proxyconnection.touch.dofus.com/assetMap.json  get
> main.bundle.js:7398 end !
> main.bundle.js:7374 https://raw.githubusercontent.com/Clover-Lindo/lindo-game-base/master/manifest.json  ok 200 null
> main.bundle.js:7398 end !
> main.bundle.js:7374 https://proxyconnection.touch.dofus.com/manifest.json  ok 200 null
> main.bundle.js:7398 end !
> main.bundle.js:7374 https://proxyconnection.touch.dofus.com/assetMap.json  ok 200 null
> main.bundle.js:7181 3
> main.bundle.js:7189 4
> main.bundle.js:1973 [UPDATE] Updating required files
> main.bundle.js:7199 5
> main.bundle.js:7205 5 bis
> main.bundle.js:7558 downloadMissingFiles Object
> main.bundle.js:7372 https://raw.githubusercontent.com/Clover-Lindo/lindo-game-base/master/fixes.js  get
> main.bundle.js:7558 downloadMissingFiles Object
> main.bundle.js:7372 https://proxyconnection.touch.dofus.com/build/styles-native.css  get

This time, fixes.js and styles-native.css gives no response.
However, the bug don't always happens.
I'll try to find a solution.

**Comment by sudogooglex** [comment]
I tryed to update "request" to "2.88.0", same error

**Comment by sudogooglex** [comment]
I have added a timeout in the request, to stop after 2 seconds :
`let options = {url: url, timeout: 1000};
request(options, (err, response, body) => {`

instead of

`request(url, (err, response, body) => {`

and then it works again.

**Comment by Dylvn** [comment]
Hi,
I get stuck too in downloading on Pop_OS!

**Comment by ElKroko** [comment]
Hi there, I had the same problem when I tried to update Lindo, and the solution that worked for me was  removing the .config directory of Lindo

`sudo rm -r ~/.config/lindo`

Be sure to check out that your Lindo folder is whether called "lindo" or "Lindo", depends on your setup.
