### ISSUE TITLE
Follow group isnt working

### ISSUE THREAD

**Issue by feesignoretti** [prixe/lindo#78]
Feature "Following group leader" on Windows is not working.
Any solutions?

**Comment by JulienCoutault** [comment]
This feature only works if the leader is play in the "same Lindo"

**Comment by Clover-Lindo** [comment]
In additionto the comment above:
The followers need info that is not always forwarded by the game itself. If the follower is not yet on the same map as the leader, it will ignore the next move. To prevent this behavior, the leader puts all actions into a buffer, which allows followers to read that buffer even if they're a few steps behind.
